from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from NetworkTrainer import *
from PyQt5.QtGui import QPixmap
import sys

class Ui_home_page(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.window_loaded = False
        
        
    def setupUi(self, home_page):
        self.current_image_prev = None
        home_page.setObjectName("home_page")
        home_page.resize(361, 400)
        self.home_page = home_page
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(home_page.sizePolicy().hasHeightForWidth())
        home_page.setSizePolicy(sizePolicy)
        home_page.setMinimumSize(QtCore.QSize(361, 400))
        home_page.setMaximumSize(QtCore.QSize(361, 400))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        home_page.setPalette(palette)
        self.tittle_label = QtWidgets.QLabel(home_page)
        self.tittle_label.setGeometry(QtCore.QRect(60, -30, 250, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.tittle_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tittle_label.setFont(font)
        self.tittle_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tittle_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tittle_label.setTextFormat(QtCore.Qt.RichText)
        self.tittle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tittle_label.setWordWrap(True)
        self.tittle_label.setIndent(0)
        self.tittle_label.setObjectName("tittle_label")
        self.predict_button = QtWidgets.QPushButton(home_page)
        self.predict_button.setGeometry(QtCore.QRect(280, 360, 71, 31))
        self.predict_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.predict_button.setAutoDefault(True)
        self.predict_button.setDefault(False)
        self.predict_button.setFlat(False)
        self.predict_button.setObjectName("predict_button")
        self.predict_button.clicked.connect(self.beginPredict)
        self.result_label = QtWidgets.QLabel(home_page)
        self.result_label.setEnabled(False)
        self.result_label.setGeometry(QtCore.QRect(70, 58, 200, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.result_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.result_label.setFont(font)
        self.result_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.result_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.result_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.result_label.setLineWidth(0)
        self.result_label.setText("")
        self.result_label.setTextFormat(QtCore.Qt.AutoText)
        self.result_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.result_label.setWordWrap(True)
        self.result_label.setIndent(0)
        self.result_label.setObjectName("result_label")
        self.image_preview_2 = QtWidgets.QLabel(home_page)
        self.image_preview_2.setGeometry(QtCore.QRect(110, 60, 141, 131))
        self.image_preview_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.image_preview_2.setText("")
        self.image_preview_2.setPixmap(QtGui.QPixmap("./UITemplates/image_preview.png"))
        self.image_preview_2.setScaledContents(True)
        self.image_preview_2.setObjectName("image_preview_2")
        self.label_2 = QtWidgets.QLabel(home_page)
        self.label_2.setGeometry(QtCore.QRect(30, 240, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(8)
        font.setItalic(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(home_page)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.import_button = QtWidgets.QPushButton(home_page)
        self.import_button.setGeometry(QtCore.QRect(120, 310, 121, 31))
        self.import_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.import_button.setAutoDefault(True)
        self.import_button.setDefault(False)
        self.import_button.setFlat(False)
        self.import_button.setObjectName("import_button")
        self.import_button.clicked.connect(self.openFileDialog)
        self.line = QtWidgets.QFrame(home_page)
        self.line.setGeometry(QtCore.QRect(17, 220, 331, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")

        self.model_selectio_button = QtWidgets.QPushButton(home_page)
        self.model_selectio_button.setGeometry(QtCore.QRect(10, 360, 111, 31))
        self.model_selectio_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.model_selectio_button.setAutoDefault(True)
        self.model_selectio_button.setDefault(False)
        self.model_selectio_button.setFlat(False)
        self.model_selectio_button.setText("< CHOOSE MODEL")
        self.model_selectio_button.clicked.connect(self.buttonModelPage)
        self.model_selectio_button.setObjectName("model_selectio_button")
        #self.model_selectio_button.clicked.connect()
        self.window_loaded = True
        self.retranslateUi(home_page)
        QtCore.QMetaObject.connectSlotsByName(home_page)

    def retranslateUi(self, home_page):
        _translate = QtCore.QCoreApplication.translate
        home_page.setWindowTitle(_translate("home_page", "Dialog"))
        self.tittle_label.setText(_translate("home_page", "Alzheimers Identifier"))
        self.predict_button.setText(_translate("home_page", "Predict >"))
        self.label_2.setText(_translate("home_page", "For a reliable prediction do make sure that the brain is at the centre of the image with a black background for better results. Image should be .png, .jpg, .bmp"))
        self.label_3.setText(_translate("home_page", "Predict an Image Below"))
        self.import_button.setText(_translate("home_page", "[ IMPORT IMAGE ]"))

    def buttonModelPage(self):
        if modelSelectWin.window_loaded == False:
                modelSelectWin.setupUi(modelSelectWin)
        modelSelectWin.resetWindow()
        modelSelectWin.listModels()
        widget.setCurrentIndex(0)
        
    def openFileDialog(self):
        #Open a file dialog
        filename, _ = QFileDialog.getOpenFileName(self.home_page, "[ IMPORT IMAGE ]", "", "Image Files (*.png *.jpg *.bmp)")
        if filename:
            #Load the image and display it in the label
            self.image_preview_2.setPixmap(QPixmap(filename))
            self.current_image_prev = filename
            
    def resetWindow(self):
        # Clear any previous data or state in the current window
        self.current_image_prev = None
        self.image_preview_2.setPixmap(QtGui.QPixmap("./UITemplates/image_preview.png"))
        # Reset any widgets or variables that need to be cleared
    def beginPredict(self): 
        if self.current_image_prev != None and os.path.exists(self.current_image_prev):
            if loadWin.window_loaded == False:
                loadWin.setupUi(loadWin)
            prev_img = self.current_image_prev
            loadWin.image_preview.setPixmap(QtGui.QPixmap(self.current_image_prev))
            widget.setCurrentIndex(2)
            output = PredictResult(self.current_image_prev, modelSelectWin.chosen_model)
            self.resetWindow()
            
            counter = 0 
            loadWin.progressBar.setValue(0)
            while counter < 100:
                loadWin.progressBar.setValue(counter)
                counter += 1
                time.sleep(.1)
            
            loadWin.resetWindow()
            if resultWin.window_loaded == False:
                resultWin.setupUi(resultWin)
                
            resultWin.setupOutput(output, prev_img)
            widget.setCurrentIndex(3)
            
          
            
class Ui_model_selection(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.window_loaded = False
        self.chosen_model = None
        self.model_no_record = {}
         
    def setupUi(self, model_selection):
        model_selection.setObjectName("model_selection")
        model_selection.resize(361, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(model_selection.sizePolicy().hasHeightForWidth())     
        model_selection.setSizePolicy(sizePolicy)
        model_selection.setMinimumSize(QtCore.QSize(361, 400))
        model_selection.setMaximumSize(QtCore.QSize(361, 400))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)        
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)       
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)        
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)       
        model_selection.setPalette(palette)
        self.tittle_label = QtWidgets.QLabel(model_selection)
        self.tittle_label.setGeometry(QtCore.QRect(29, -40, 301, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)        
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)        
        self.tittle_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tittle_label.setFont(font)
        self.tittle_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tittle_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tittle_label.setTextFormat(QtCore.Qt.RichText)
        self.tittle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tittle_label.setWordWrap(True)
        self.tittle_label.setIndent(0)
        self.tittle_label.setObjectName("tittle_label")
        self.text_facts = QtWidgets.QLabel(model_selection)
        self.text_facts.setGeometry(QtCore.QRect(30, 240, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(8)
        font.setItalic(False)
        font.setKerning(True)
        self.text_facts.setFont(font)
        self.text_facts.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.text_facts.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.text_facts.setWordWrap(True)
        self.text_facts.setObjectName("text_facts")
        self.text_fact2 = QtWidgets.QLabel(model_selection)
        self.text_fact2.setGeometry(QtCore.QRect(30, 40, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(9)
        font.setItalic(False)
        font.setKerning(True)
        self.text_fact2.setFont(font)
        self.text_fact2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_fact2.setAlignment(QtCore.Qt.AlignCenter)
        self.text_fact2.setObjectName("text_fact2")
        self.choose_button = QtWidgets.QPushButton(model_selection)
        self.choose_button.setGeometry(QtCore.QRect(120, 310, 121, 31))
        self.choose_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.choose_button.setAutoDefault(True)
        self.choose_button.setDefault(False)
        self.choose_button.setFlat(False)
        self.choose_button.setObjectName("choose_button")
        self.choose_button.clicked.connect(self.homeButtonClicked)
        self.line = QtWidgets.QFrame(model_selection)
        self.line.setGeometry(QtCore.QRect(17, 220, 331, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayoutWidget = QtWidgets.QWidget(model_selection)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 90, 301, 127))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vLayout.setContentsMargins(0, 0, 0, 40)
        self.vLayout.setSpacing(0)
        self.vLayout.setObjectName("vLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.vLayout.addWidget(self.pushButton)

        self.retranslateUi(model_selection)
        QtCore.QMetaObject.connectSlotsByName(model_selection)
        self.resetWindow()
        self.listModels()
        self.window_loaded = True
    def retranslateUi(self, model_selection):
        _translate = QtCore.QCoreApplication.translate
        model_selection.setWindowTitle(_translate("model_selection", "Dialog"))
        self.tittle_label.setText(_translate("model_selection", "Alzheimers Identifier"))  
        self.text_facts.setText(_translate("model_selection", "You must select a model from the existing models in the list, once selected click on the choose model button to proceed."))
        self.text_fact2.setText(_translate("model_selection", "Choose from the models available below to predict with!"))
        self.choose_button.setText(_translate("model_selection", "[CHOOSE MODEL]"))        
        self.pushButton.setText(_translate("model_selection", "PushButton"))     
        
    
    def homeButtonClicked(self):
        if self.chosen_model != None:
            if homeWin.window_loaded == False:
                homeWin.setupUi(homeWin)
            homeWin.resetWindow()
            widget.setCurrentIndex(1)
    
    def resetWindow(self):
        self.chosen_model = None
        self.model_no_record = {}
        for i in reversed(range(self.vLayout.count())):
            item = self.vLayout.itemAt(i)
            if isinstance(item.widget(), QtWidgets.QPushButton):
                button = item.widget()
                self.vLayout.removeWidget(button)
                button.setParent(None)
                button.deleteLater()
        
    def listModels(self):
        
            
        for i in reversed(range(self.vLayout.count())):
            item = self.vLayout.itemAt(i)
            if isinstance(item.widget(), QtWidgets.QPushButton):
                button = item.widget()
                self.vLayout.removeWidget(button)
                button.setParent(None)
                button.deleteLater()
                
        dir = "./TrainingLogs"
       
        for filename in os.listdir(dir):
            filepath = os.path.join(dir, filename)
            if os.path.isdir(dir + "/" + filename) and (os.path.exists(dir + "/" + filename + "/model_data.npy") or os.path.exists(dir + "/" + filename + "/model_data.h5")):
                def buttonClicked():
                    sender = self.sender()  # Get the sender of the signal (the clicked button)
                    for model_no, button in self.model_no_record.items():
                        if button == sender:
                            self.chosen_model = str(model_no)
                            break
                    

                button = QtWidgets.QPushButton(self.verticalLayoutWidget)
                self.model_no_record[int(filename[-1])] = button
                button.setObjectName("button_" + str(filename[-1]))
                button.setText("Model: "+str(filename[-1]))
                button.clicked.connect(buttonClicked)
                self.vLayout.addWidget(button)
        
        

class Ui_result_page(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.window_loaded = False
        
    def setupUi(self, result_page):
        result_page.setObjectName("result_page")
        result_page.resize(361, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(result_page.sizePolicy().hasHeightForWidth())
        result_page.setSizePolicy(sizePolicy)
        result_page.setMinimumSize(QtCore.QSize(361, 400))
        result_page.setMaximumSize(QtCore.QSize(361, 400))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        result_page.setPalette(palette)
        self.tittle_label = QtWidgets.QLabel(result_page)
        self.tittle_label.setGeometry(QtCore.QRect(60, -30, 250, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.tittle_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tittle_label.setFont(font)
        self.tittle_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tittle_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tittle_label.setTextFormat(QtCore.Qt.RichText)
        self.tittle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tittle_label.setWordWrap(True)
        self.tittle_label.setIndent(0)
        self.tittle_label.setObjectName("tittle_label")
        self.predict_button = QtWidgets.QPushButton(result_page)
        self.predict_button.setGeometry(QtCore.QRect(90, 360, 191, 31))
        self.predict_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.predict_button.setAutoDefault(True)
        self.predict_button.setDefault(False)
        self.predict_button.setFlat(False)
        self.predict_button.setObjectName("predict_button")
        self.result_label = QtWidgets.QLabel(result_page)
        self.result_label.setEnabled(False)
        self.result_label.setGeometry(QtCore.QRect(70, 58, 200, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.result_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.result_label.setFont(font)
        self.result_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.result_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.result_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.result_label.setLineWidth(0)
        self.result_label.setText("")
        self.result_label.setTextFormat(QtCore.Qt.AutoText)
        self.result_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.result_label.setWordWrap(True)
        self.result_label.setIndent(0)
        self.result_label.setObjectName("result_label")
        self.image_preview_2 = QtWidgets.QLabel(result_page)
        self.image_preview_2.setGeometry(QtCore.QRect(110, 52, 141, 131))
        self.image_preview_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.image_preview_2.setText("")
        self.image_preview_2.setPixmap(QtGui.QPixmap("./UITemplates/image_preview.png"))
        self.image_preview_2.setScaledContents(True)
        self.image_preview_2.setObjectName("image_preview_2")
        
        
        
        
        self.label = QtWidgets.QLabel(result_page)
        self.label.setGeometry(QtCore.QRect(10, 270, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(result_page)
        self.label_2.setGeometry(QtCore.QRect(10, 220, 341, 21))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(result_page)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(result_page)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        _translate = QtCore.QCoreApplication.translate
        result_page.setWindowTitle(_translate("result_page", "Dialog"))
        self.tittle_label.setText(_translate("result_page", "Alzheimers Identifier"))
        self.predict_button.setText(_translate("result_page", "[ PREDICT MORE IMAGES ]"))
        
        self.predict_button.clicked.connect(self.backHomeButton)
        
        self.label.setText(_translate("result_page", " "))
        
        self.label_3.setText(_translate("result_page", "Predicted Result"))
        self.label_4.setText(_translate("result_page", "Detailed Results (Confidence Measures)"))
        self.window_loaded = True
        
        QtCore.QMetaObject.connectSlotsByName(result_page)

    def resetWindow(self):
        _translate = QtCore.QCoreApplication.translate
        self.image_preview_2.setPixmap(QtGui.QPixmap("./UITemplates/image_preview.png"))
        self.label.setText(_translate("result_page", " "))
        self.label_3.setText(_translate("result_page","Predicted Result"))
        self.label_4.setText(_translate("result_page","Detailed Results (Confidence Measures)"))
        
    def backHomeButton(self):
        #homeWin.image_preview_2.setPixmap(QtGui.QPixmap("./UITemplates/image_preview.png"))
        self.resetWindow()
        widget.setCurrentIndex(1)

    def setupOutput(self, results, img):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("result_page", " "))
        self.image_preview_2.setPixmap(QtGui.QPixmap(img))
        if results != None:
            predicted =  max(results, key=results.get)
            print(results)
            self.label.setText(_translate("result_page", "MildDemented: "+ str(round(results["MildDemented"], 2))+"\n"
            "ModerateDemented: "+ str(round(results["ModerateDemented"], 2))+"\n"
            "NonDemented: "+ str(round(results["NonDemented"], 2))+"\n"
            "VeryMildDemented: "+ str(round(results["VeryMildDemented"], 2))))
            self.label_2.setText(_translate("result_page", "Brain Condition: "+str(predicted)))
        else:
            self.label_2.setText(_translate("result_page", "Brain Condition: Unkown"))
        self.label_3.setText(_translate("result_page", "Predicted Result"))
        self.label_4.setText(_translate("result_page", "Detailed Results (Confidence Measures)"))        



class Ui_loading_page(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.window_loaded = False
        
        
    def setupUi(self, loading_page):
        loading_page.setObjectName("loading_page")
        loading_page.resize(361, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(loading_page.sizePolicy().hasHeightForWidth())
        loading_page.setSizePolicy(sizePolicy)
        loading_page.setMinimumSize(QtCore.QSize(361, 400))
        loading_page.setMaximumSize(QtCore.QSize(361, 400))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 230, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        loading_page.setPalette(palette)
        self.tittle_label = QtWidgets.QLabel(loading_page)
        self.tittle_label.setGeometry(QtCore.QRect(60, -30, 250, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.tittle_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tittle_label.setFont(font)
        self.tittle_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tittle_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tittle_label.setTextFormat(QtCore.Qt.RichText)
        self.tittle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tittle_label.setWordWrap(True)
        self.tittle_label.setIndent(0)
        self.tittle_label.setObjectName("tittle_label")
        self.help_text = QtWidgets.QLabel(loading_page)
        self.help_text.setGeometry(QtCore.QRect(60, 250, 250, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.help_text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.help_text.setFont(font)
        self.help_text.setInputMethodHints(QtCore.Qt.ImhNone)
        self.help_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.help_text.setFrameShadow(QtWidgets.QFrame.Plain)
        self.help_text.setTextFormat(QtCore.Qt.AutoText)
        self.help_text.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.help_text.setWordWrap(True)
        self.help_text.setIndent(0)
        self.help_text.setObjectName("help_text")
        self.image_preview = QtWidgets.QLabel(loading_page)
        self.image_preview.setGeometry(QtCore.QRect(110, 60, 141, 131))
        self.image_preview.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.image_preview.setText("")
        self.image_preview.setPixmap(QtGui.QPixmap("../../../OneDrive/Desktop/Images/image_preview.png"))
        self.image_preview.setScaledContents(True)
        self.image_preview.setObjectName("image_preview")
        self.line = QtWidgets.QFrame(loading_page)
        self.line.setGeometry(QtCore.QRect(30, 190, 301, 41))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.predict_button = QtWidgets.QPushButton(loading_page)
        self.predict_button.setGeometry(QtCore.QRect(140, 360, 81, 31))
        self.predict_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.predict_button.setAutoDefault(True)
        self.predict_button.setDefault(False)
        self.predict_button.setFlat(False)
        self.predict_button.setObjectName("predict_button")
        self.progressBar = QtWidgets.QProgressBar(loading_page)
        self.progressBar.setGeometry(QtCore.QRect(90, 230, 201, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.help_text_2 = QtWidgets.QLabel(loading_page)
        self.help_text_2.setGeometry(QtCore.QRect(10, 290, 341, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.help_text_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.help_text_2.setFont(font)
        self.help_text_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.help_text_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.help_text_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.help_text_2.setTextFormat(QtCore.Qt.AutoText)
        self.help_text_2.setAlignment(QtCore.Qt.AlignCenter)
        self.help_text_2.setWordWrap(True)
        self.help_text_2.setIndent(0)
        self.help_text_2.setObjectName("help_text_2")

        self.retranslateUi(loading_page)
        QtCore.QMetaObject.connectSlotsByName(loading_page)
        self.window_loaded = True
    def retranslateUi(self, loading_page):
        _translate = QtCore.QCoreApplication.translate
        loading_page.setWindowTitle(_translate("loading_page", "Dialog"))
        self.tittle_label.setText(_translate("loading_page", "Alzheimers Identifier"))
        self.help_text.setText(_translate("loading_page", "[ PREDICTING ]"))
        self.predict_button.setText(_translate("loading_page", "Back"))
        self.help_text_2.setText(_translate("loading_page", "Please note that the the prediction being calculated on the image is only a prediction and further research may need to be carried out after receiving the prediction to confirm that the model is 100% correct."))

    def resetWindow(self):
        loadWin.image_preview.setPixmap(QtGui.QPixmap("../../../OneDrive/Desktop/Images/image_preview.png"))




if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QStackedWidget()
    homeWin = Ui_home_page()
    loadWin = Ui_loading_page()
    resultWin = Ui_result_page()
    modelSelectWin = Ui_model_selection()
    
    widget.addWidget(modelSelectWin)
    widget.addWidget(homeWin)
    widget.addWidget(loadWin)
    widget.addWidget(resultWin)    
    
    modelSelectWin.setupUi(modelSelectWin)
    widget.show()
    
    sys.exit(app.exec_())